from django.test import TestCase
from apps.megavn.models import MegaEmployee
# Create your tests here.
data = [
    {
        "code": "MVG-0222-22",
        "group": "MEGA_GROUP",
        "department": "PKT",
        "name": "Phạm Thị Như Quỳnh",
        "other": "MVG-PKT-KT07",
        "title": "Nhân viên",
        "email": "quynh.phamnhu@megavietnam.vn",
    },
    {
        "code": "MVG-0322-20",
        "group": "MEGA_GROUP",
        "department": "PKT",
        "name": "Nguyễn Minh Hiền",
        "other": "MVG-PKT-KT05",
        "title": "Nhân viên",
        "email": "hien.nguyenminh@megavietnam.vn",
    },
    {
        "code": "MVG-0324-01",
        "group": "MEGA_GROUP",
        "department": "VT",
        "name": "Vũ Duy Đông",
        "other": "MVG-VT-LX01",
        "title": "Trưởng nhóm",
        "email": None,
    },
    {
        "code": "MVG-0324-02",
        "group": "MEGA_GROUP",
        "department": "VT",
        "name": "Nguyễn Điệp Hoa",
        "other": "MVG-VT-LX02",
        "title": "Lái xe",
        "email": None,
    },
    {
        "code": "MVG-0324-03",
        "group": "MEGA_GROUP",
        "department": "NSHN",
        "name": "Vũ Văn Thủy",
        "other": "MVG-PHC-LX03",
        "title": "Lái xe",
        "email": None,
    },
    {
        "code": "MVG-0422-02",
        "group": "MEGA_GROUP",
        "department": "NSHN",
        "name": "Đoàn Thị Huyền",
        "other": "MVG-PHC-NV02",
        "title": "Nhân viên",
        "email": "huyen.doanthi@megavietnam.vn",
    },
    {
        "code": "MVG-0423-029",
        "group": "MEGA_GROUP",
        "department": "ADMIN-HN",
        "name": "Nguyễn Thị Thu Hằng",
        "other": "MVG-PMH-AD08",
        "title": "Nhân viên",
        "email": "hang.nguyenthithu@megavietnam.vn",
    },
    {
        "code": "MVG-0423-031",
        "group": "MEGA_GROUP",
        "department": "ADMIN-HN",
        "name": "Nguyễn Ngọc Bảo Ly",
        "other": "MVG-PMH-AD07",
        "title": "Nhân viên",
        "email": "ly.nguyenngocbao@megavietnam.vn",
    },
    {
        "code": "MVG-0521-11",
        "group": "MEGA_GROUP",
        "department": "PCDS",
        "name": "Ngô Văn Thắng",
        "other": "MVG-CDS-NV05",
        "title": "Trưởng nhóm",
        "email": "thang.ngovan@megavietnam.vn",
    },
    {
        "code": "MVG-0623-02",
        "group": "MEGA_GROUP",
        "department": "NSHN",
        "name": "Nguyễn Thị Thủy Tiên",
        "other": "MVG-PHC-NV03",
        "title": "Nhân viên",
        "email": "tien.nguyenthithuy@megavietnam.vn",
    },
    {
        "code": "MVG-0624-01",
        "group": "MEGA_GROUP",
        "department": "PKT",
        "name": "Trịnh Thị Vân Anh",
        "other": "",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVG-0624-02",
        "group": "MEGA_GROUP",
        "department": "PKT",
        "name": "Nguyễn Ngọc Anh",
        "other": "",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVG-0624-03",
        "group": "MEGA_GROUP",
        "department": "PKT",
        "name": "Đặng Thị Phương Nga",
        "other": "",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVG-0624-06",
        "group": "MEGA_GROUP",
        "department": "PKT",
        "name": "Bùi Thị Xuân",
        "other": "MVG-PKT-KT06",
        "title": "Nhân viên",
        "email": "xuan.buithi@megavietnam.vn",
    },
    {
        "code": "MVG-0720-09",
        "group": "MEGA_GROUP",
        "department": "PCDS",
        "name": "Nguyễn Chương Đức",
        "other": "MVG-CDS-NV04",
        "title": "Nhân viên",
        "email": "duc.nguyenchuong@megavietnam.vn",
    },
    {
        "code": "MVG-0723-02",
        "group": "MEGA_GROUP",
        "department": "PKT",
        "name": "Phạm Thị Kiều Trang",
        "other": "MVG-PKT-KT02",
        "title": "Kế toán trưởng",
        "email": "trang.phamthikieu@megavietnam.vn",
    },
    {
        "code": "MVG-0818-04",
        "group": "MEGA_GROUP",
        "department": "TGD",
        "name": "Vũ Thị Huệ",
        "other": "MVG-BGD-GD03",
        "title": "Giám đốc",
        "email": "hue.vuthi@megavietnam.vn",
    },
    {
        "code": "MVG-0818-05",
        "group": "MEGA_GROUP",
        "department": "PTT",
        "name": "Lê Công Du",
        "other": "MVG-CDS-NV01",
        "title": "Nhân viên",
        "email": "du.lecong@megavietnam.vn",
    },
    {
        "code": "MVG-1018-06",
        "group": "MEGA_GROUP",
        "department": "PKT",
        "name": "Vũ Thị Hòa",
        "other": "MVG-BGD-GD04",
        "title": "Kế toán trưởng",
        "email": "hoa.vuthi@megavietnam.vn",
    },
    {
        "code": "MVG-1022-25",
        "group": "MEGA_GROUP",
        "department": "KHOHCM",
        "name": "Đinh Thị Phương",
        "other": "MVT-PMH-TK03",
        "title": "Nhân viên",
        "email": "phuong.dinhthi@megavietnam.vn",
    },
    {
        "code": "MVP-0222-01",
        "group": "MEGA_RD",
        "department": "SX",
        "name": "Nguyễn Văn Thương",
        "other": "MVP-QLSX-NV01",
        "title": "Trưởng BP",
        "email": "thuong.nguyenvan@megavietnam.vn",
    },
    {
        "code": "MVP-0302-05",
        "group": "MEGA_RD",
        "department": "XSX",
        "name": "Phàn Cầu Páo",
        "other": "",
        "title": None,
        "email": "pao.phancau@megavietnam.vn",
    },
    {
        "code": "MVP-0523-03",
        "group": "MEGA_RD",
        "department": "SX",
        "name": "Phàn Văn Hà",
        "other": "MVP-SX-NV02",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVP-0523-03",
        "group": "MEGA_GROUP",
        "department": "SX",
        "name": "Phàn Văn Hà",
        "other": "MVP-SX-NV02",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVP-0524-04",
        "group": "MEGA_RD",
        "department": "SX",
        "name": "Nguyễn Xuân Đức",
        "other": "",
        "title": None,
        "email": None,
    },
    {
        "code": "MVP-0622-01",
        "group": "MEGA_RD",
        "department": "SX",
        "name": "Giàng A Pó",
        "other": "MVP-SX-NV01",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVP-0624-01",
        "group": "MEGA_RD",
        "department": "SX",
        "name": "Nguyễn Thị Thơm",
        "other": "MVP-QC-NV01",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVP-0723-03",
        "group": "MEGA_RD",
        "department": "SX",
        "name": "Trương Việt Hoàng",
        "other": "MVP-SX-NV03",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVP-0724-01",
        "group": "MEGA_RD",
        "department": "SX",
        "name": "Chu Xuân Quỳnh",
        "other": "",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVR-0124-17",
        "group": "MEGA_TRADING",
        "department": "SP",
        "name": "Nguyễn Thị Mơ",
        "other": "MVR-PRD-NV17",
        "title": "Nhân viên",
        "email": "mo.nguyenthi@megavietnam.vn",
    },
    {
        "code": "MVR-0124-17",
        "group": "MEGA_GROUP",
        "department": "SP",
        "name": "Nguyễn Thị Mơ",
        "other": "MVR-PRD-NV17",
        "title": "Nhân viên",
        "email": "mo.nguyenthi@megavietnam.vn",
    },
    {
        "code": "MVR-0124-17",
        "group": "MEGA_RD",
        "department": "SP",
        "name": "Nguyễn Thị Mơ",
        "other": "MVR-PRD-NV17",
        "title": "Nhân viên",
        "email": "mo.nguyenthi@megavietnam.vn",
    },
    {
        "code": "MVR-0220-03",
        "group": "MEGA_RD",
        "department": "AK",
        "name": "Nguyễn Văn Vượng",
        "other": "MVR-PRD-NV03",
        "title": "Nhân viên",
        "email": "vuong.nguyenvan@megavietnam.vn",
    },
    {
        "code": "MVR-0220-03",
        "group": "MEGA_PRO",
        "department": "PNCPT",
        "name": "Nguyễn Văn Vượng",
        "other": "MVR-PRD-NV03",
        "title": "Nhân viên",
        "email": "vuong.nguyenvan@megavietnam.vn",
    },
    {
        "code": "MVR-0220-03",
        "group": "MEGA_GROUP",
        "department": "PNCPT",
        "name": "Nguyễn Văn Vượng",
        "other": "MVR-PRD-NV03",
        "title": "Nhân viên",
        "email": "vuong.nguyenvan@megavietnam.vn",
    },
    {
        "code": "MVR-0220-03",
        "group": "MEGA_TRADING",
        "department": "R&D",
        "name": "Nguyễn Văn Vượng",
        "other": "MVR-PRD-NV03",
        "title": "Nhân viên",
        "email": "vuong.nguyenvan@megavietnam.vn",
    },
    {
        "code": "MVR-0321-14",
        "group": "MEGA_TRADING",
        "department": "PQC",
        "name": "Nguyễn Thị Giang",
        "other": "MVR-PRD-NV02",
        "title": "Nhân viên",
        "email": "duongnguyenthuy005@gmail.com",
    },
    {
        "code": "MVR-0321-14",
        "group": "MEGA_PRO",
        "department": "EW",
        "name": "Nguyễn Thị Giang",
        "other": "MVR-PRD-NV02",
        "title": "Trưởng nhóm",
        "email": "duongnguyenthuy005@gmail.com",
    },
    {
        "code": "MVR-0321-14",
        "group": "MEGA_RD",
        "department": "EW",
        "name": "Nguyễn Thị Giang",
        "other": "MVR-PRD-NV02",
        "title": "Nhân viên",
        "email": "duongnguyenthuy005@gmail.com",
    },
    {
        "code": "MVR-0321-14",
        "group": "MEGA_GROUP",
        "department": "EW",
        "name": "Nguyễn Thị Giang",
        "other": "MVR-PRD-NV02",
        "title": "Trưởng nhóm",
        "email": "duongnguyenthuy005@gmail.com",
    },
    {
        "code": "MVR-0520-05",
        "group": "MEGA_PRO",
        "department": "PKT",
        "name": "Nguyễn Thị Trang",
        "other": "MVR-KTT-KT01",
        "title": "Nhân viên",
        "email": "trang.nguyenthi@megavietnam.vn",
    },
    {
        "code": "MVR-0520-05",
        "group": "MEGA_GROUP",
        "department": "PKT",
        "name": "Nguyễn Thị Trang",
        "other": "MVR-KTT-KT01",
        "title": "Nhân viên",
        "email": "trang.nguyenthi@megavietnam.vn",
    },
    {
        "code": "MVR-0520-05",
        "group": "MEGA_TRADING",
        "department": "KT",
        "name": "Nguyễn Thị Trang",
        "other": "MVR-KTT-KT01",
        "title": "Nhân viên",
        "email": "trang.nguyenthi@megavietnam.vn",
    },
    {
        "code": "MVR-0520-05",
        "group": "MEGA_RD",
        "department": "KT",
        "name": "Nguyễn Thị Trang",
        "other": "MVR-KTT-KT01",
        "title": "Nhân viên",
        "email": "trang.nguyenthi@megavietnam.vn",
    },
    {
        "code": "MVR-0522-002",
        "group": "MEGA_RD",
        "department": "AK",
        "name": "Ngô Quang Trường",
        "other": "MVR-PRD-NV07",
        "title": "Nhân viên",
        "email": "bigzeronumber@gmail.com",
    },
    {
        "code": "MVR-0624-05",
        "group": "MEGA_TRADING",
        "department": "PNCPT",
        "name": "Đỗ Xuân Huy",
        "other": "MVR-PRD-NV05",
        "title": "Trưởng nhóm",
        "email": "huy.doxuan@megavietnam.vn",
    },
    {
        "code": "MVR-0624-05",
        "group": "MEGA_PRO",
        "department": "PNCPT",
        "name": "Đỗ Xuân Huy",
        "other": "MVR-PRD-NV05",
        "title": "Trưởng nhóm",
        "email": "huy.doxuan@megavietnam.vn",
    },
    {
        "code": "MVR-0624-05",
        "group": "MEGA_GROUP",
        "department": "PNCPT",
        "name": "Đỗ Xuân Huy",
        "other": "MVR-PRD-NV05",
        "title": "Trưởng nhóm",
        "email": "huy.doxuan@megavietnam.vn",
    },
    {
        "code": "MVR-0624-05",
        "group": "MEGA_RD",
        "department": "PNCPT",
        "name": "Đỗ Xuân Huy",
        "other": "MVR-PRD-NV05",
        "title": "Trưởng nhóm",
        "email": "huy.doxuan@megavietnam.vn",
    },
    {
        "code": "MVR-0720-06",
        "group": "MEGA_TRADING",
        "department": "PKD1",
        "name": "Bùi Hoàng Anh",
        "other": "MVR-PRD-NV06",
        "title": "Nhân viên",
        "email": "anh.buihoang@megavietnam.vn",
    },
    {
        "code": "MVR-0720-06",
        "group": "MEGA_RD",
        "department": "PKD1",
        "name": "Bùi Hoàng Anh",
        "other": "MVR-PRD-NV06",
        "title": "Nhân viên Telesale",
        "email": "anh.buihoang@megavietnam.vn",
    },
    {
        "code": "MVR-0720-06",
        "group": "MEGA_PRO",
        "department": "PTL",
        "name": "Bùi Hoàng Anh",
        "other": "MVR-PRD-NV06",
        "title": "Nhân viên Telesale",
        "email": "anh.buihoang@megavietnam.vn",
    },
    {
        "code": "MVR-0720-06",
        "group": "MEGA_GROUP",
        "department": "PTL",
        "name": "Bùi Hoàng Anh",
        "other": "MVR-PRD-NV06",
        "title": "Nhân viên Telesale",
        "email": "anh.buihoang@megavietnam.vn",
    },
    {
        "code": "MVR-1219-01",
        "group": "MEGA_GROUP",
        "department": "SP",
        "name": "Trịnh Văn Lợi",
        "other": "MVR-PRD-NV01",
        "title": "Trưởng nhóm",
        "email": "loi.trinhvan@megavietnam.vn",
    },
    {
        "code": "MVR-1219-01",
        "group": "MEGA_PRO",
        "department": "SP",
        "name": "Trịnh Văn Lợi",
        "other": "MVR-PRD-NV01",
        "title": "Trưởng nhóm",
        "email": "loi.trinhvan@megavietnam.vn",
    },
    {
        "code": "MVR-1219-01",
        "group": "MEGA_TRADING",
        "department": "R&D",
        "name": "Trịnh Văn Lợi",
        "other": "MVR-PRD-NV01",
        "title": "Nhân viên 1",
        "email": "loi.trinhvan@megavietnam.vn",
    },
    {
        "code": "MVR-1219-01",
        "group": "MEGA_RD",
        "department": "SP",
        "name": "Trịnh Văn Lợi",
        "other": "MVR-PRD-NV01",
        "title": "Trưởng nhóm",
        "email": "loi.trinhvan@megavietnam.vn",
    },
    {
        "code": "MVR-1222-12",
        "group": "MEGA_RD",
        "department": "AK",
        "name": "Lưu Thị Dung",
        "other": "MVR-PRD-NV12",
        "title": "Nhân viên",
        "email": "dung.luuthi@megavietnam.vn",
    },
    {
        "code": "MVR-1222-12",
        "group": "MEGA_TRADING",
        "department": "SP02",
        "name": "Lưu Thị Dung",
        "other": "MVR-PRD-NV12",
        "title": "Trưởng nhóm",
        "email": "dung.luuthi@megavietnam.vn",
    },
    {
        "code": "MVR-1222-12",
        "group": "MEGA_GROUP",
        "department": "SP02",
        "name": "Lưu Thị Dung",
        "other": "MVR-PRD-NV12",
        "title": "Trưởng nhóm",
        "email": "dung.luuthi@megavietnam.vn",
    },
    {
        "code": "MVR-1222-12",
        "group": "MEGA_PRO",
        "department": "SP02",
        "name": "Lưu Thị Dung",
        "other": "MVR-PRD-NV12",
        "title": "Trưởng nhóm",
        "email": "dung.luuthi@megavietnam.vn",
    },
    {
        "code": "MVT-0115-01",
        "group": "MEGA_TRADING",
        "department": "PMH",
        "name": "Nguyễn Thúy Hà",
        "other": "MVT-PMH-AD01",
        "title": "Trưởng BP",
        "email": "ha.nguyenthuy@megavietnam.vn",
    },
    {
        "code": "MVT-0115-01",
        "group": "MEGA_PRO",
        "department": "KHO",
        "name": "Nguyễn Thúy Hà",
        "other": "MVT-PMH-AD01",
        "title": "Trưởng nhóm",
        "email": "ha.nguyenthuy@megavietnam.vn",
    },
    {
        "code": "MVT-0115-01",
        "group": "MEGA_RD",
        "department": "Admin",
        "name": "Nguyễn Thúy Hà",
        "other": "MVT-PMH-AD01",
        "title": "Trưởng nhóm",
        "email": "ha.nguyenthuy@megavietnam.vn",
    },
    {
        "code": "MVT-0115-01",
        "group": "MEGA_GROUP",
        "department": "ADMIN-HN",
        "name": "Nguyễn Thúy Hà",
        "other": "MVT-PMH-AD01",
        "title": "Trưởng nhóm",
        "email": "ha.nguyenthuy@megavietnam.vn",
    },
    {
        "code": "MVT-0118-08",
        "group": "MEGA_RD",
        "department": "PKD1",
        "name": "Phạm Văn An",
        "other": "MVT-PKD-NV01",
        "title": "Trưởng phòng",
        "email": "an.phamvan@megavietnam.vn",
    },
    {
        "code": "MVT-0118-08",
        "group": "MEGA_PRO",
        "department": "PKD1",
        "name": "Phạm Văn An",
        "other": "MVT-PKD-NV01",
        "title": "Trưởng phòng",
        "email": "an.phamvan@megavietnam.vn",
    },
    {
        "code": "MVT-0118-08",
        "group": "MEGA_TRADING",
        "department": "PKD1",
        "name": "Phạm Văn An",
        "other": "MVT-PKD-NV01",
        "title": "Trưởng nhóm",
        "email": "an.phamvan@megavietnam.vn",
    },
    {
        "code": "MVT-0118-08",
        "group": "MEGA_GROUP",
        "department": "PKD1",
        "name": "Phạm Văn An",
        "other": "MVT-PKD-NV01",
        "title": "Trưởng phòng",
        "email": "an.phamvan@megavietnam.vn",
    },
    {
        "code": "MVT-0122-12",
        "group": "MEGA_TRADING",
        "department": "PKD2",
        "name": "Hoàng Như Quỳnh",
        "other": "MVT-PKD-NV10",
        "title": "Nhân viên Telesale",
        "email": "quynh.hoangnhu@megavietnam.vn",
    },
    {
        "code": "MVT-0122-12",
        "group": "MEGA_RD",
        "department": "PKD2",
        "name": "Hoàng Như Quỳnh",
        "other": "MVT-PKD-NV10",
        "title": "Nhân viên Telesale",
        "email": "quynh.hoangnhu@megavietnam.vn",
    },
    {
        "code": "MVT-0122-12",
        "group": "MEGA_PRO",
        "department": "PKD2",
        "name": "Hoàng Như Quỳnh",
        "other": "MVT-PKD-NV10",
        "title": "Nhân viên Telesale",
        "email": "quynh.hoangnhu@megavietnam.vn",
    },
    {
        "code": "MVT-0122-12",
        "group": "MEGA_GROUP",
        "department": "PKD2",
        "name": "Hoàng Như Quỳnh",
        "other": "MVT-PKD-NV10",
        "title": "Nhân viên Telesale",
        "email": "quynh.hoangnhu@megavietnam.vn",
    },
    {
        "code": "MVT-0122-15",
        "group": "MEGA_RD",
        "department": "PKD5",
        "name": "Huỳnh Vũ Tuấn Hà",
        "other": "MVT-PKD-NV11",
        "title": "Trưởng nhóm",
        "email": "ha.huynhvutuan@megavietnam.vn",
    },
    {
        "code": "MVT-0122-15",
        "group": "MEGA_TRADING",
        "department": "PKD5",
        "name": "Huỳnh Vũ Tuấn Hà",
        "other": "MVT-PKD-NV11",
        "title": "Trưởng nhóm",
        "email": "ha.huynhvutuan@megavietnam.vn",
    },
    {
        "code": "MVT-0122-15",
        "group": "MEGA_GROUP",
        "department": "PKD5",
        "name": "Huỳnh Vũ Tuấn Hà",
        "other": "MVT-PKD-NV11",
        "title": "Trưởng phòng",
        "email": "ha.huynhvutuan@megavietnam.vn",
    },
    {
        "code": "MVT-0122-15",
        "group": "MEGA_PRO",
        "department": "PKD5",
        "name": "Huỳnh Vũ Tuấn Hà",
        "other": "MVT-PKD-NV11",
        "title": "Trưởng phòng",
        "email": "ha.huynhvutuan@megavietnam.vn",
    },
    {
        "code": "MVT-0217-06",
        "group": "MEGA_GROUP",
        "department": "NSHN",
        "name": "Phạm Thị Nhung",
        "other": "MVT-PHC-NV01",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVT-0217-06",
        "group": "MEGA_RD",
        "department": "HCNS",
        "name": "Phạm Thị Nhung",
        "other": "MVT-PHC-NV01",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVT-0217-06",
        "group": "MEGA_TRADING",
        "department": "NSHN",
        "name": "Phạm Thị Nhung",
        "other": "MVT-PHC-NV01",
        "title": "Tạp vụ",
        "email": None,
    },
    {
        "code": "MVT-0217-06",
        "group": "MEGA_PRO",
        "department": "DVHC",
        "name": "Phạm Thị Nhung",
        "other": "MVT-PHC-NV01",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVT-0320-15",
        "group": "MEGA_RD",
        "department": "Admin",
        "name": "Vũ Thị Minh Huyền",
        "other": "MVT-PMH-TK01",
        "title": "Nhân viên",
        "email": "huyen.vuthiminh@megavietnam.vn",
    },
    {
        "code": "MVT-0320-15",
        "group": "MEGA_TRADING",
        "department": "PMH",
        "name": "Vũ Thị Minh Huyền",
        "other": "MVT-PMH-TK01",
        "title": "Thủ kho",
        "email": "huyen.vuthiminh@megavietnam.vn",
    },
    {
        "code": "MVT-0320-15",
        "group": "MEGA_GROUP",
        "department": "KHOHN",
        "name": "Vũ Thị Minh Huyền",
        "other": "MVT-PMH-TK01",
        "title": "Nhân viên",
        "email": "huyen.vuthiminh@megavietnam.vn",
    },
    {
        "code": "MVT-0320-15",
        "group": "MEGA_PRO",
        "department": "KHO",
        "name": "Vũ Thị Minh Huyền",
        "other": "MVT-PMH-TK01",
        "title": "Nhân VIên",
        "email": "huyen.vuthiminh@megavietnam.vn",
    },
    {
        "code": "MVT-0323-05",
        "group": "MEGA_GROUP",
        "department": "PKD3",
        "name": "Phan Tấn Thành",
        "other": "MVT-PKD-NV05",
        "title": "Nhân viên",
        "email": "thanh.phantan@megavietnam.vn",
    },
    {
        "code": "MVT-0323-05",
        "group": "MEGA_RD",
        "department": "PKD3",
        "name": "Phan Tấn Thành",
        "other": "MVT-PKD-NV05",
        "title": "Nhân viên",
        "email": "thanh.phantan@megavietnam.vn",
    },
    {
        "code": "MVT-0323-05",
        "group": "MEGA_TRADING",
        "department": "PKD3",
        "name": "Phan Tấn Thành",
        "other": "MVT-PKD-NV05",
        "title": "Trưởng nhóm",
        "email": "thanh.phantan@megavietnam.vn",
    },
    {
        "code": "MVT-0323-05",
        "group": "MEGA_PRO",
        "department": "PKD3",
        "name": "Phan Tấn Thành",
        "other": "MVT-PKD-NV05",
        "title": "Nhân viên",
        "email": "thanh.phantan@megavietnam.vn",
    },
    {
        "code": "MVT-0323-20",
        "group": "MEGA_PRO",
        "department": "PKD4",
        "name": "Mai Mạnh Hữu",
        "other": "MVT-PKD-NV20",
        "title": "Nhân viên",
        "email": "huu.maimanh@megavietnam.vn",
    },
    {
        "code": "MVT-0323-20",
        "group": "MEGA_RD",
        "department": "PKD4",
        "name": "Mai Mạnh Hữu",
        "other": "MVT-PKD-NV20",
        "title": "Nhân viên",
        "email": "huu.maimanh@megavietnam.vn",
    },
    {
        "code": "MVT-0323-20",
        "group": "MEGA_GROUP",
        "department": "PKD4",
        "name": "Mai Mạnh Hữu",
        "other": "MVT-PKD-NV20",
        "title": "Nhân viên",
        "email": "huu.maimanh@megavietnam.vn",
    },
    {
        "code": "MVT-0323-20",
        "group": "MEGA_TRADING",
        "department": "PKD4",
        "name": "Mai Mạnh Hữu",
        "other": "MVT-PKD-NV20",
        "title": "Nhân viên",
        "email": "huu.maimanh@megavietnam.vn",
    },
    {
        "code": "MVT-0416-04",
        "group": "MEGA_PRO",
        "department": "HCNS",
        "name": "Hoàng Minh Đoàn",
        "other": "MVG-PHC-LX01",
        "title": "Nhân viên lái xe",
        "email": None,
    },
    {
        "code": "MVT-0416-04",
        "group": "MEGA_GROUP",
        "department": "NSHN",
        "name": "Hoàng Minh Đoàn",
        "other": "MVG-PHC-LX01",
        "title": "Lái xe",
        "email": None,
    },
    {
        "code": "MVT-0416-04",
        "group": "MEGA_RD",
        "department": "HCNS",
        "name": "Hoàng Minh Đoàn",
        "other": "MVG-PHC-LX01",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVT-0416-04",
        "group": "MEGA_TRADING",
        "department": "NSHN",
        "name": "Hoàng Minh Đoàn",
        "other": "MVG-PHC-LX01",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVT-0418-09",
        "group": "MEGA_GROUP",
        "department": "PKH",
        "name": "Nguyễn Văn Việt",
        "other": "MVT-PKD-NV07",
        "title": "Trưởng phòng",
        "email": "viet.nguyenvan@megavietnam.vn",
    },
    {
        "code": "MVT-0418-09",
        "group": "MEGA_PRO",
        "department": "PKD3",
        "name": "Nguyễn Văn Việt",
        "other": "MVT-PKD-NV07",
        "title": "Trưởng phòng",
        "email": "viet.nguyenvan@megavietnam.vn",
    },
    {
        "code": "MVT-0418-09",
        "group": "MEGA_RD",
        "department": "PKD3",
        "name": "Nguyễn Văn Việt",
        "other": "MVT-PKD-NV07",
        "title": "Trưởng nhóm",
        "email": "viet.nguyenvan@megavietnam.vn",
    },
    {
        "code": "MVT-0418-09",
        "group": "MEGA_TRADING",
        "department": "PKD4",
        "name": "Nguyễn Văn Việt",
        "other": "MVT-PKD-NV07",
        "title": "Trưởng nhóm",
        "email": "viet.nguyenvan@megavietnam.vn",
    },
    {
        "code": "MVT-0423-020",
        "group": "MEGA_GROUP",
        "department": "PKD1",
        "name": "Dương Doãn Nhật",
        "other": "MVT-PKD-NV25",
        "title": "Nhân viên",
        "email": "nhatduongdoan@megavietnam.vn",
    },
    {
        "code": "MVT-0423-020",
        "group": "MEGA_TRADING",
        "department": "PKD1",
        "name": "Dương Doãn Nhật",
        "other": "MVT-PKD-NV25",
        "title": "Nhân viên",
        "email": "nhatduongdoan@megavietnam.vn",
    },
    {
        "code": "MVT-0423-020",
        "group": "MEGA_PRO",
        "department": "PKD1",
        "name": "Dương Doãn Nhật",
        "other": "MVT-PKD-NV25",
        "title": "Nhân viên",
        "email": "nhatduongdoan@megavietnam.vn",
    },
    {
        "code": "MVT-0423-020",
        "group": "MEGA_RD",
        "department": "PKD1",
        "name": "Dương Doãn Nhật",
        "other": "MVT-PKD-NV25",
        "title": "Nhân viên",
        "email": "nhatduongdoan@megavietnam.vn",
    },
    {
        "code": "MVT-0423-022",
        "group": "MEGA_GROUP",
        "department": "PKD2",
        "name": "Nguyễn Thị Ngọc Mai",
        "other": "MVT-PKD-NV21",
        "title": "Nhân viên Telesale",
        "email": "mai.nguyenthingo@megavietnam.vn",
    },
    {
        "code": "MVT-0423-022",
        "group": "MEGA_TRADING",
        "department": "PKD2",
        "name": "Nguyễn Thị Ngọc Mai",
        "other": "MVT-PKD-NV21",
        "title": "Nhân viên",
        "email": "mai.nguyenthingo@megavietnam.vn",
    },
    {
        "code": "MVT-0423-022",
        "group": "MEGA_RD",
        "department": "PKD2",
        "name": "Nguyễn Thị Ngọc Mai",
        "other": "MVT-PKD-NV21",
        "title": "Nhân viên Telesale",
        "email": "mai.nguyenthingo@megavietnam.vn",
    },
    {
        "code": "MVT-0423-022",
        "group": "MEGA_PRO",
        "department": "PKD2",
        "name": "Nguyễn Thị Ngọc Mai",
        "other": "MVT-PKD-NV21",
        "title": "Nhân viên Telesale",
        "email": "mai.nguyenthingo@megavietnam.vn",
    },
    {
        "code": "MVT-0423-027",
        "group": "MEGA_RD",
        "department": "PKD2",
        "name": "Cù Thị Linh",
        "other": "MVT-PKD-NV27",
        "title": "Nhân viên Telesale",
        "email": "linh.cuthi@megavietnam.vn",
    },
    {
        "code": "MVT-0423-027",
        "group": "MEGA_GROUP",
        "department": "PKD2",
        "name": "Cù Thị Linh",
        "other": "MVT-PKD-NV27",
        "title": "Nhân viên Telesale",
        "email": "linh.cuthi@megavietnam.vn",
    },
    {
        "code": "MVT-0423-027",
        "group": "MEGA_TRADING",
        "department": "PKD2",
        "name": "Cù Thị Linh",
        "other": "MVT-PKD-NV27",
        "title": "Nhân viên Telesale",
        "email": "linh.cuthi@megavietnam.vn",
    },
    {
        "code": "MVT-0423-027",
        "group": "MEGA_PRO",
        "department": "PKD2",
        "name": "Cù Thị Linh",
        "other": "MVT-PKD-NV27",
        "title": "Nhân viên Telesale",
        "email": "linh.cuthi@megavietnam.vn",
    },
    {
        "code": "MVT-0423-24",
        "group": "MEGA_RD",
        "department": "PKD4",
        "name": "Trương Quốc Việt",
        "other": "MVT-PKD-NV24",
        "title": "Nhân viên",
        "email": "viet.truongquoc@megavietnam.vn",
    },
    {
        "code": "MVT-0423-24",
        "group": "MEGA_TRADING",
        "department": "PKD4",
        "name": "Trương Quốc Việt",
        "other": "MVT-PKD-NV24",
        "title": "Nhân viên",
        "email": "viet.truongquoc@megavietnam.vn",
    },
    {
        "code": "MVT-0423-24",
        "group": "MEGA_PRO",
        "department": "PKD4",
        "name": "Trương Quốc Việt",
        "other": "MVT-PKD-NV24",
        "title": "Nhân viên",
        "email": "viet.truongquoc@megavietnam.vn",
    },
    {
        "code": "MVT-0423-24",
        "group": "MEGA_GROUP",
        "department": "PKD4",
        "name": "Trương Quốc Việt",
        "other": "MVT-PKD-NV24",
        "title": "Nhân viên",
        "email": "viet.truongquoc@megavietnam.vn",
    },
    {
        "code": "MVT-0506-04",
        "group": "MEGA_TRADING",
        "department": "PKD1",
        "name": "Đỗ Thị Kiều Oanh",
        "other": "MVR-PRD-NV04",
        "title": "Nhân viên",
        "email": "oanh.dothikieu@megavietnam.vn",
    },
    {
        "code": "MVT-0523-14",
        "group": "MEGA_TRADING",
        "department": "PKD3",
        "name": "Quách Hoàng Kha",
        "other": "MVT-PKD-NV14",
        "title": "Nhân viên",
        "email": "kha.quachhoang@megavietnam.vn",
    },
    {
        "code": "MVT-0524-22",
        "group": "MEGA_TRADING",
        "department": "PKD5",
        "name": "Trần Thị Kim Ngân",
        "other": "MVT-PKD-NV22",
        "title": "Nhân viên",
        "email": "ngan.tranthikim@megavietnam.vn",
    },
    {
        "code": "MVT-0623-18",
        "group": "MEGA_TRADING",
        "department": "PKD3",
        "name": "Nguyễn Duy Linh",
        "other": "MVT-PKD-NV18",
        "title": "Nhân viên",
        "email": "linh.nguyenduy@megavietnam.vn",
    },
    {
        "code": "MVT-0624-12",
        "group": "MEGA_PRO",
        "department": "PKD5",
        "name": "Lê Trọng Khang",
        "other": "MVT-PKD-NV12",
        "title": "Nhân viên",
        "email": "khang.letrong@megavietnam.vn",
    },
    {
        "code": "MVT-0624-12",
        "group": "MEGA_RD",
        "department": "PKD5",
        "name": "Lê Trọng Khang",
        "other": "MVT-PKD-NV12",
        "title": "Nhân viên",
        "email": "khang.letrong@megavietnam.vn",
    },
    {
        "code": "MVT-0624-12",
        "group": "MEGA_TRADING",
        "department": "PKD5",
        "name": "Lê Trọng Khang",
        "other": "MVT-PKD-NV12",
        "title": "Nhân viên",
        "email": "khang.letrong@megavietnam.vn",
    },
    {
        "code": "MVT-0624-12",
        "group": "MEGA_GROUP",
        "department": "PKD5",
        "name": "Lê Trọng Khang",
        "other": "MVT-PKD-NV12",
        "title": "Nhân viên",
        "email": "khang.letrong@megavietnam.vn",
    },
    {
        "code": "MVT-0624-26",
        "group": "MEGA_TRADING",
        "department": "PKD3",
        "name": "Hoàng Vân Anh",
        "other": "MVT-PKD-NV26",
        "title": "Nhân viên",
        "email": "anh.hoangvan@megavietnam.vn",
    },
    {
        "code": "MVT-0715-02",
        "group": "MEGA_RD",
        "department": "PCDS",
        "name": "Hoàng Cao Huyên",
        "other": "MVT-BGD-GD05",
        "title": "Giám đốc",
        "email": "huyen.hoangcao@megavietnam.vn",
    },
    {
        "code": "MVT-0715-02",
        "group": "MEGA_PRO",
        "department": "BPSX",
        "name": "Hoàng Cao Huyên",
        "other": "MVT-BGD-GD05",
        "title": "Giám đốc",
        "email": "huyen.hoangcao@megavietnam.vn",
    },
    {
        "code": "MVT-0715-02",
        "group": "MEGA_TRADING",
        "department": "BGD",
        "name": "Hoàng Cao Huyên",
        "other": "MVT-BGD-GD05",
        "title": "Giám đốc",
        "email": "huyen.hoangcao@megavietnam.vn",
    },
    {
        "code": "MVT-0715-02",
        "group": "MEGA_GROUP",
        "department": "DVHC",
        "name": "Hoàng Cao Huyên",
        "other": "MVT-BGD-GD05",
        "title": "Giám đốc",
        "email": "huyen.hoangcao@megavietnam.vn",
    },
    {
        "code": "MVT-0716-05",
        "group": "MEGA_TRADING",
        "department": "PKD2",
        "name": "Hoàng Thị Mai Linh",
        "other": "MVT-PKD-NV04",
        "title": "Nhân viên",
        "email": "linh.hoangmai@megavietnam.vn",
    },
    {
        "code": "MVT-0716-05",
        "group": "MEGA_GROUP",
        "department": "kHTH",
        "name": "Hoàng Thị Mai Linh",
        "other": "MVT-PKD-NV04",
        "title": "Nhân viên",
        "email": "linh.hoangmai@megavietnam.vn",
    },
    {
        "code": "MVT-0716-05",
        "group": "MEGA_RD",
        "department": "PKD2",
        "name": "Hoàng Thị Mai Linh",
        "other": "MVT-PKD-NV04",
        "title": "Nhân viên",
        "email": "linh.hoangmai@megavietnam.vn",
    },
    {
        "code": "MVT-0716-05",
        "group": "MEGA_PRO",
        "department": "PKD2",
        "name": "Hoàng Thị Mai Linh",
        "other": "MVT-PKD-NV04",
        "title": "Nhân viên",
        "email": "linh.hoangmai@megavietnam.vn",
    },
    {
        "code": "MVT-0720-17",
        "group": "MEGA_TRADING",
        "department": "NSHCM",
        "name": "Phan Duy Nhã",
        "other": "MVG-PHC-LX02",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVT-0720-17",
        "group": "MEGA_PRO",
        "department": "HCNS",
        "name": "Phan Duy Nhã",
        "other": "MVG-PHC-LX02",
        "title": "Nhân viên lái xe",
        "email": None,
    },
    {
        "code": "MVT-0720-17",
        "group": "MEGA_GROUP",
        "department": "NSHCM",
        "name": "Phan Duy Nhã",
        "other": "MVG-PHC-LX02",
        "title": "Lái xe",
        "email": None,
    },
    {
        "code": "MVT-0720-17",
        "group": "MEGA_RD",
        "department": "HCNS",
        "name": "Phan Duy Nhã",
        "other": "MVG-PHC-LX02",
        "title": "Nhân viên",
        "email": None,
    },
    {
        "code": "MVT-0724-15",
        "group": "MEGA_TRADING",
        "department": "PKD4",
        "name": "Phan Quốc An",
        "other": "MVT-PKD-NV15",
        "title": "Nhân viên",
        "email": "an.phanquoc@megavietnam.vn",
    },
    {
        "code": "MVT-0724-23",
        "group": "MEGA_PRO",
        "department": "PKD3",
        "name": "Trần Đinh Đại Nhân",
        "other": "MVT-PKD-NV23",
        "title": "Nhân viên",
        "email": "nhan.trandinhdai@megavietnam.vn",
    },
    {
        "code": "MVT-0724-23",
        "group": "MEGA_GROUP",
        "department": "PKD3",
        "name": "Trần Đinh Đại Nhân",
        "other": "MVT-PKD-NV23",
        "title": "Nhân viên",
        "email": "nhan.trandinhdai@megavietnam.vn",
    },
    {
        "code": "MVT-0724-23",
        "group": "MEGA_TRADING",
        "department": "PKD3",
        "name": "Trần Đinh Đại Nhân",
        "other": "MVT-PKD-NV23",
        "title": "Nhân viên",
        "email": "nhan.trandinhdai@megavietnam.vn",
    },
    {
        "code": "MVT-0724-23",
        "group": "MEGA_RD",
        "department": "PKD3",
        "name": "Trần Đinh Đại Nhân",
        "other": "MVT-PKD-NV23",
        "title": "Nhân viên",
        "email": "nhan.trandinhdai@megavietnam.vn",
    },
    {
        "code": "MVT-0918-10",
        "group": "MEGA_TRADING",
        "department": "PMH",
        "name": "Hoàng Thị Hương",
        "other": "MVT-PMH-AD03",
        "title": "Trưởng phòng",
        "email": "huong.hoangthi@megavietnam.vn",
    },
    {
        "code": "MVT-0918-10",
        "group": "MEGA_RD",
        "department": "HCNS",
        "name": "Hoàng Thị Hương",
        "other": "MVT-PMH-AD03",
        "title": "Trưởng nhóm",
        "email": "huong.hoangthi@megavietnam.vn",
    },
    {
        "code": "MVT-0918-10",
        "group": "MEGA_GROUP",
        "department": "ADMIN-HCM",
        "name": "Hoàng Thị Hương",
        "other": "MVT-PMH-AD03",
        "title": "Trưởng nhóm",
        "email": "huong.hoangthi@megavietnam.vn",
    },
    {
        "code": "MVT-0918-10",
        "group": "MEGA_PRO",
        "department": "PVTNL",
        "name": "Hoàng Thị Hương",
        "other": "MVT-PMH-AD03",
        "title": "Trưởng nhóm",
        "email": "huong.hoangthi@megavietnam.vn",
    },
    {
        "code": "MVT-1117-07",
        "group": "MEGA_PRO",
        "department": "PKD2",
        "name": "Phạm Thị Huyền",
        "other": "MVT-PKD-NV03",
        "title": "Trưởng BP",
        "email": "huyen.phamthi@megavietnam.vn",
    },
    {
        "code": "MVT-1117-07",
        "group": "MEGA_RD",
        "department": "PKD2",
        "name": "Phạm Thị Huyền",
        "other": "MVT-PKD-NV03",
        "title": "Trưởng BP",
        "email": "huyen.phamthi@megavietnam.vn",
    },
    {
        "code": "MVT-1117-07",
        "group": "MEGA_GROUP",
        "department": "PKD2",
        "name": "Phạm Thị Huyền",
        "other": "MVT-PKD-NV03",
        "title": "Trưởng BP",
        "email": "huyen.phamthi@megavietnam.vn",
    },
    {
        "code": "MVT-1117-07",
        "group": "MEGA_TRADING",
        "department": "PKD2",
        "name": "Phạm Thị Huyền",
        "other": "MVT-PKD-NV03",
        "title": "Trưởng nhóm",
        "email": "huyen.phamthi@megavietnam.vn",
    },
    {
        "code": "MVT-1122-19",
        "group": "MEGA_TRADING",
        "department": "PKD4",
        "name": "Trần Bá Nhất Anh",
        "other": "MVT-PKD-NV19",
        "title": "Nhân viên",
        "email": "anh.tranbanhat@megavietnam.vn",
    },
    {
        "code": "MVT-1123-016",
        "group": "MEGA_TRADING",
        "department": "PKD3",
        "name": "Trần Thị Hường",
        "other": "MVT-PKD-NV16",
        "title": "Nhân viên",
        "email": "huong.tranthi@megavietnam.vn",
    },
    {
        "code": "MVT2704-17",
        "group": "MEGA_GROUP",
        "department": "PTL",
        "name": "Phạm Thị Phương Thảo",
        "other": "MVT-PKD-NV17",
        "title": "Nhân viên Telesale",
        "email": "thao.phamthiphuong@megavietnam.vn",
    },
    {
        "code": "MVT2704-17",
        "group": "MEGA_PRO",
        "department": "PTL",
        "name": "Phạm Thị Phương Thảo",
        "other": "MVT-PKD-NV17",
        "title": "Nhân viên Telesale",
        "email": "thao.phamthiphuong@megavietnam.vn",
    },
    {
        "code": "MVT2704-17",
        "group": "MEGA_TRADING",
        "department": "PKD1",
        "name": "Phạm Thị Phương Thảo",
        "other": "MVT-PKD-NV17",
        "title": "Nhân viên Telesale",
        "email": "thao.phamthiphuong@megavietnam.vn",
    },
    {
        "code": "MVT2704-17",
        "group": "MEGA_RD",
        "department": "PTL",
        "name": "Phạm Thị Phương Thảo",
        "other": "MVT-PKD-NV17",
        "title": "Nhân viên Telesale",
        "email": "thao.phamthiphuong@megavietnam.vn",
    },
]
def import_data():
    for item in data:
        try:
            employee = MegaEmployee(code=item['code'], 
                        group=item['group'], 
                        department=item['department'], 
                        name=item['name'], 
                        other=item['other'], 
                        title=item['title'],
                        email=item['email'])
            employee.save()
        except Exception as ex:
            print(f'{data} - {ex}')
            try:
                employee = MegaEmployee(code=item['other'], 
                            group=item['group'], 
                            department=item['department'], 
                            name=item['name'], 
                            other=item['other'], 
                            title=item['title'],
                            email=item['email'])
                employee.save()
            except Exception as ex2:
                print(f'ex 2: {data} - {ex2}')
    