import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import { Refine, ResourceProps } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import {
  CloudUpload,
  DriveFileRenameOutlineOutlined,
  TrackChangesOutlined,
  GradingOutlined,
  HomeOutlined,
  AssessmentOutlined,
} from "@mui/icons-material";

import { dataProvider } from "@providers/data-provider";
import MuiRegistry from "@/lib/mui-registry";
import "./style.css";
import { AppIcon } from "@components/app-icon";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProviderClient } from "@providers/auth-provider/auth-provider.client";
import { getAccessibleResources } from "@utils/server/get-accessible-resources";
import { Noto_Sans_JP } from "next/font/google";

const notoSansJP = Noto_Sans_JP({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
  display: "swap",
});

export const metadata: Metadata = {
  title: "DNP Project",
  description: "Generated by Data Impact",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  let userRoles: string[] = [];
  const authCookie = cookieStore.get("auth");
  if (authCookie) {
    try {
      const user = JSON.parse(authCookie.value);
      console.log("user XXX", user.roles);
      userRoles = user.roles || [];
    } catch (e) {
      userRoles = [];
    }
  }

  return (
    <html lang="jp" className={notoSansJP.className}>
      <body>
        <Suspense>
          {/* <GitHubBanner /> */}
          <RefineKbarProvider>
            <MuiRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <Refine
                  routerProvider={routerProvider}
                  dataProvider={dataProvider}
                  authProvider={authProviderClient}
                  resources={getAccessibleResources(allResources, userRoles)}
                  options={{
                    syncWithLocation: true,
                    useNewQueryKeys: true,
                  }}
                >
                  {children}
                  <RefineKbar />
                </Refine>
              </ColorModeContextProvider>
            </MuiRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}

const allResources: ResourceProps[] = [
  {
    name: "top-teacher",
    list: "/top-teacher",
    meta: {
      canDelete: true,
      label: "Top Teacher",
      icon: <HomeOutlined sx={{ fontSize: "28px" }} />,
    },
  },
  {
    name: "top-student",
    list: "/top-student",
    meta: {
      canDelete: true,
      label: "Top Student",
      icon: <HomeOutlined sx={{ fontSize: "26px" }} />,
    },
  },
  {
    name: "goals-setup",
    list: "/goals-setup",
    meta: {
      canDelete: true,
      label: "目標設定",
      icon: <TrackChangesOutlined sx={{ fontSize: "26px" }} />,
    },
  },
  {
    name: "daily-progress-teacher",
    list: "/daily-progress-teacher",
    meta: {
      create: "/daily-progress-teacher/create",
      canDelete: true,
      label: "日々の学習記録",
      icon: <DriveFileRenameOutlineOutlined sx={{ fontSize: "26px" }} />,
    },
  },
  {
    name: "daily-progress-student",
    list: "/daily-progress-student",
    meta: {
      canDelete: true,
      label: "日々の学習記録",
      icon: <DriveFileRenameOutlineOutlined sx={{ fontSize: "24px" }} />,
    },
  },
  {
    name: "tests-review",
    list: "/tests-review",
    show: "/test-view-teacher/:id",
    meta: {
      canDelete: true,
      label: "テスト振り返り",
      icon: <GradingOutlined sx={{ fontSize: "24px" }} />,
    },
  },
  {
    name: "learning-overview",
    list: "/learning-overview",
    meta: {
      canDelete: true,
      label: "学習全体の振り返り",
      icon: <AssessmentOutlined sx={{ fontSize: "24px" }} />,
    },
  },
  {
    name: "learning-data-entry",
    list: "/learning-data-entry",
    meta: {
      create: "/learning-data-entry/create",
      canDelete: true,
      label: "学習データ登録",
      icon: <CloudUpload sx={{ color: "var(--color-yellow)" }} />,
    },
  },
  // Will continue at new version
  // {
  //   name: "grading",
  //   list: "/grading",
  //   meta: {
  //     canDelete: true,
  //     label: "採点",
  //     icon: <AssignmentTurnedIn sx={{ fontSize: "24px" }} color="primary" />,
  //   },
  // },
  // {
  //   name: "analysis-dashboard",
  //   list: "/analysis-dashboard",
  //   meta: {
  //     canDelete: true,
  //     label: "総合分析 ダッシュボード",
  //     icon: <Dashboard sx={{ fontSize: "24px" }} color="primary" />,
  //   },
  // },
  // {
  //   name: "management",
  //   meta: { label: "共通", canDelete: true },
  // },
  // {
  //   name: "instructors",
  //   meta: { label: "指導者", canDelete: true },
  // },
  // {
  //   name: "learners",
  //   meta: { label: "学習者", canDelete: true },
  // },
  // {
  //   name: "pdfuploads",
  //   list: "/pdfuploads",
  //   meta: {
  //     canDelete: true,
  //     label: "問題PDF UL+設問分析連携",
  //     parent: "instructors",
  //   },
  // },
  // {
  //   name: "WAO LIB",
  //   list: "/weight",
  //   meta: {
  //     canDelete: true,
  //     label: "WAO LIB",
  //     parent: "instructors",
  //   },
  // },
  // {
  //   name: "先生",
  //   list: "/teacher-test",
  //   meta: {
  //     canDelete: true,
  //     label: "先生",
  //     parent: "instructors",
  //   },
  // },
  // {
  //   name: "leaning_logs",
  //   list: "/learning-logs",
  //   meta: {
  //     canDelete: true,
  //     label: "学習ログUL+登録確認",
  //     parent: "instructors",
  //   },
  // },
  // {
  //   name: "result_analysis",
  //   list: "/result-analysis",
  //   create: "/result-analysis/create",
  //   edit: "/result-analysis/edit/:id",
  //   show: "/result-analysis/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label: "分析結果（個票・帳票）DL",
  //     parent: "instructors",
  //   },
  // },
  // {
  //   name: "teaching_support_tools",
  //   list: "/blog-posts",
  //   create: "/blog-posts/create",
  //   edit: "/blog-posts/edit/:id",
  //   show: "/blog-posts/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label: "指導支援ツールリンク",
  //     parent: "instructors",
  //   },
  // },
  // {
  //   name: "english-notebooks",
  //   list: "/english-notebooks",
  //   meta: {
  //     canDelete: true,
  //     label: "英語罫線ノート",
  //     parent: "teaching_support_tools",
  //   },
  // },
  // {
  //   name: "alphabet_tables",
  //   list: "/alphabet-tables",
  //   meta: {
  //     canDelete: true,
  //     label: "アルファベット表",
  //     parent: "teaching_support_tools",
  //   },
  // },
  // {
  //   name: "alphabet_practice_prints",
  //   list: "/alphabet-practice-prints",
  //   meta: {
  //     canDelete: true,
  //     label: "アルファベット練習プリント",
  //     parent: "teaching_support_tools",
  //   },
  // },
  // {
  //   name: "test_papers",
  //   list: "/test-papers",
  //   meta: {
  //     canDelete: true,
  //     label:
  //       "小学校で習う英単語700語の練習・テスト・単語帳・ポスター・絵カード",
  //     parent: "teaching_support_tools",
  //   },
  // },
  // {
  //   name: "te_link",
  //   list: "/blog-posts",
  //   create: "/blog-posts/create",
  //   edit: "/blog-posts/edit/:id",
  //   show: "/blog-posts/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label: "TEリンク",
  //     parent: "instructors",
  //   },
  // },
  // {
  //   name: "teenglish-notebooks",
  //   list: "/english-notebooks",
  //   meta: {
  //     canDelete: true,
  //     label: "英語罫線ノート",
  //     parent: "te_link",
  //   },
  // },
  // {
  //   name: "tealphabet_table",
  //   list: "/posts",
  //   create: "/posts/create",
  //   edit: "/posts/edit/:id",
  //   show: "/posts/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label: "アルファベット表",
  //     parent: "te_link",
  //   },
  // },
  // {
  //   name: "te_alphabet_practice_prints",
  //   list: "/blog-posts",
  //   create: "/blog-posts/create",
  //   edit: "/blog-posts/edit/:id",
  //   show: "/blog-posts/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label: "アルファベット練習プリント",
  //     parent: "te_link",
  //   },
  // },
  // {
  //   name: "te_test_papers",
  //   list: "/test-papers",
  //   create: "/test-papers/create",
  //   edit: "/test-papers/edit/:id",
  //   show: "/test-papers/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label:
  //       "小学校で習う英単語700語の練習・テスト・単語帳・ポスター・絵カード",
  //     parent: "te_link",
  //   },
  // },
  // {
  //   name: "account_management_links",
  //   list: "/blog-posts",
  //   create: "/blog-posts/create",
  //   edit: "/blog-posts/edit/:id",
  //   show: "/blog-posts/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label: "アカウント管理リンク",
  //     parent: "instructors",
  //   },
  // },
  // {
  //   name: "outside_portal_links",
  //   list: "/blog-posts",
  //   create: "/blog-posts/create",
  //   edit: "/blog-posts/edit/:id",
  //   show: "/blog-posts/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label: "書棚ポータル",
  //     parent: "management",
  //   },
  // },
  // {
  //   name: "activity_logs",
  //   list: "/blog-posts",
  //   create: "/blog-posts/create",
  //   edit: "/blog-posts/edit/:id",
  //   show: "/blog-posts/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label: "操作ログ蓄積",
  //     parent: "management",
  //   },
  // },
  // {
  //   name: "students-test",
  //   list: "/students-test",
  //   create: "/students-test/create",
  //   edit: "/students-test/edit/:id",
  //   show: "/students-test/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label: "児童・生徒画面",
  //     parent: "learners",
  //   },
  // },
  // {
  //   name: "semester-midterm-test",
  //   list: "/semester-midterm-test",
  //   meta: {
  //     canDelete: true,
  //     label: "テスト結果",
  //     parent: "learners",
  //   },
  // },
  // {
  //   name: "result-student-total",
  //   list: "/result-student-total",
  //   meta: {
  //     canDelete: true,
  //     label: "面談用ダッシュボード",
  //     parent: "learners",
  //   },
  // },
  // {
  //   name: "blog_posts",
  //   list: "/blog-posts",
  //   create: "/blog-posts/create",
  //   edit: "/blog-posts/edit/:id",
  //   show: "/blog-posts/show/:id",
  //   meta: {
  //     canDelete: true,
  //     label: "学びの支援ツールリンク",
  //     parent: "learners",
  //   },
  // },
  // {
  //   name: "categories",
  //   list: "/categories",
  //   create: "/categories/create",
  //   edit: "/categories/edit/:id",
  //   show: "/categories/show/:id",
  //   meta: {
  //     canDelete: true,
  //     parent: "learners",
  //   },
  // },
  // {
  //   name: "students",
  //   list: "/students",
  //   meta: {
  //     canDelete: true,
  //     label: "Danh sách học sinh",
  //     parent: "management",
  //   },
  // },
  // {
  //   name: "teachers",
  //   list: "/teachers",
  //   meta: {
  //     canDelete: true,
  //     label: "Danh sách giáo viên",
  //     parent: "management",
  //   },
  // },
];
