version: '3.8'
services:
  btmh-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
      - redis_network
    depends_on:
      - db
      - redis
    ports:
      - "5005:5005"
    entrypoint: ["/bin/bash", "-c", "./wait-for-postgres.sh db python manage.py migrate && ./wait-for-postgres.sh db daphne -b 0.0.0.0 -p 5005 core.asgi:application"]

  celery-worker:
    container_name: celery_worker
    restart: always
    build: .
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - btmh-app
    networks:
      - db_network
      - redis_network

  celery-beat:
    container_name: celery_beat
    restart: always
    build: .
    command: celery -A core beat --loglevel=info
    depends_on:
      - redis
      - btmh-app
    networks:
      - db_network
      - redis_network

  redis:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis_network

  db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appseed_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - btmh-app

  odoo-db:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    networks:
      - odoo_network
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo18:
    image: odoo:18
    user: root
    depends_on:
      - odoo-db
    ports:
      - "10017:8069"
      - "20017:8072"
    tty: true
    command: --
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=odoo18@2024
      - PIP_BREAK_SYSTEM_PACKAGES=1
    networks:
      - odoo_network
      - web_network
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always

networks:
  odoo_network:
    driver: bridge
  db_network:
    driver: bridge
  web_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  postgres_data:
