FROM python:3.9

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements_web.txt requirements.txt
# install python dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY apps ./apps
COPY cli ./cli
COPY config ./config
COPY nginx ./nginx
COPY static ./static
COPY staticfiles ./staticfiles
COPY templates ./templates
COPY test ./test
COPY *.py ./
COPY *.sh ./
COPY *.md ./
COPY *.ini ./
COPY *.txt ./
COPY *.json ./

# running migrations
RUN python manage.py migrate
RUN python manage.py collectstatic --no-input
# chạy bằng runserver
CMD ["python", "manage.py", "runserver", "0.0.0.0:5005"]
