# Generated by Django 5.2.6 on 2025-10-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('id_card_number', models.CharField(max_length=20, unique=True)),
                ('old_id_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('other_id_card_number', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('english_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('info', models.JSONField(blank=True, help_text='Thông tin về store profile', null=True)),
            ],
        ),
    ]
